version: '3.3'

services:
    backend:
        build: backend
        ports:
            - "8080:8080"
        environment:
            - GIN_MODE=debug
            - emailPW=prejacksudhod
            - dbUser=admin
            - dbPW=preryusudhod
    frontend:
        build: frontend
        ports:
            - "80:80"
        links:
            - backend:backend
        depends_on:
            - backend
        environment:
            - PORT=80
        
