definitions:
  responses.GetVerifReqResponse:
    properties:
      userIds:
        example:
        - 1
        - 2
        items:
          type: integer
        type: array
    type: object
  utils.ResponseMessage:
    properties:
      message:
        example: message
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/user/verifRequest:
    post:
      consumes:
      - application/json
      description: user create verification request to be verify user
      operationId: CreateVerificationReqHandler
      parameters:
      - default: Bearer <Add access token here>
        description: token of user who make request
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.ResponseMessage'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ResponseMessage'
      summary: user create verification request
      tags:
      - user
  /api/v1/user/verifRequests:
    get:
      consumes:
      - application/json
      description: admin want to get all verification requests
      operationId: GetVerificationReqsHandler
      parameters:
      - default: Bearer <Add access token here>
        description: admin token
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.GetVerifReqResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ResponseMessage'
      summary: admin view all verification requests
      tags:
      - user
swagger: "2.0"
